### DISCUSSION TITLE
Python custom types

### DISCUSSION THREAD

**Discussion by blade47** [cross-language-cpp/djinni-generator#137] [Q&A]
Good evening, 

First of all, thank you very much for your support!
I am writing a custom type that allows input/output of OpenCV Mat to and from C++.
Everything is working fine in Java and ObjectiveC++, however, I am not able to find good examples of how to define custom types using Python, mainly on how to define my YAML file in order to define typename and translator.

Is it possible?

Thank you very much!

Best regards,
Alessandro

**Comment by a4z** [comment]
Hi Allesandro, Python support is very rudimentary and requires following some a.t.m still hardcoded rules.

I started with adding an example on generating python files in my fork of the examples but then ran out of time for further stages
https://github.com/a4z/djinni-example-cc/tree/next/pysupport

Regarding what is possible,  I think the best option is to look up the in the test folder.
There is a simple [using_custom_datatypes.djinni](https://github.com/cross-language-cpp/djinni-generator/blob/main/src/it/resources/using_custom_datatypes.djinni) example that produces that output
https://github.com/cross-language-cpp/djinni-generator/tree/main/src/it/resources/expected/using_custom_datatypes/python

I'm not sure if this is a huge help for you, but that's all I have now. Sorry.

Maybe @freitass has more info on the topic

**Reply by blade47** [reply]
Hello Harald!
Thanks a lot for your answer.

Just to give you more context, I came up with the following files:

Example.yaml
```
name: Mat
typedef: 'record'
params: []
prefix: ''
cpp:
    typename: '::cv::Mat'
    header: '<opencv2/core/mat.hpp>'
    byValue: false
objc:
    typename: 'OpenCvMat'
    header: '"OpenCvMat.h"'
    boxed: 'OpenCvMat'
    pointer: true
    hash: '%s.hash'
objcpp:
    translator: '::cv::djinni::objc::CvMatConverter'
    header: '"OpenCvMat+Private.h"'
java:
    typename: 'Mat'
    boxed: '"Mat.java"'
    reference: true
    generic: true
    hash: '%s.hashCode()'
jni:
    translator: '::cv::djinni::jni::NativeMat'
    header: '"NativeMat.hpp"'
    typename: jobject
    typeSignature: 'Lorg/opencv/core/Mat;'

```

Example.djinni
```
@extern "example.yaml"

adapter = interface +c {
    static create(input: string): adapter;
    Read(mat: Mat): string;
}
```

Therefore I was wondering if I could define the Python specific translator and type into my 'example.yaml' (as for the others).

Thanks a lot!

Best regards,
Alessandro
